server:
  port: 8888
spring:
  application:
    name: yier-zuul

eureka:
  instance:
    prefer-ip-address: true
    instance-id: yier-zuul
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
zuul:
  ignored-services: "*"  #静止使用微服务名称调用
  routes:
    user:
      #比如我要调用user可能只要一个/user就好了 而不是/service-user
      serviceId: service-user
      path: /user/**
    client:
      serviceId: service-client
      path: /client/**
  prefix: /api #请求路径添加前缀
    #use-routing:
      #sensitiveHeaders:
  #sensitive-headers:
  ignoredHeaders:


feign:
  hystrix:
    enabled: false
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: full  # full | basic | none | headers
